environment:
  matrix:
    - platform: x64
      julia: 1.1
      link: "julialang/bin/winnt/x64/1.1/julia-1.1-latest-win64.exe"
    - platform: x64
      julia: 1.2
      link: "julialang/bin/winnt/x64/1.2/julia-1.2-latest-win64.exe"
    - platform: x64
      julia: nightly
      link: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:link),
        "C:\projects\julia-binary.exe")
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"PolynomialMatrices\"); Pkg.build(\"PolynomialMatrices\")"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"PolynomialMatrices\")"
